version: '3.9'

services:

    db:
        container_name: ${PROJECT_NAME}__postgres
        image: postgres:13.3
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_DB: ${DB_DATABASE}

    adminer:
        container_name: ${PROJECT_NAME}__adminer
        image: adminer
        environment:
            - ADMINER_DESIGN=pepa-linha
        ports:
            - 8081:8080

    npm:
        container_name: ${PROJECT_NAME}__node
        user: ${UID}:${GID}
        image: node:16-buster
        working_dir: /app
        volumes:
            - ./symfony:/app:cached

    php:
        container_name: ${PROJECT_NAME}__php-fpm
        build:
            context: ./docker/php-fpm
            args:
                PHP_XDEBUG_MODE: ${PHP_XDEBUG_MODE}
                PHP_XDEBUG_CLIENT_PORT: ${PHP_XDEBUG_CLIENT_PORT}
                PHP_XDEBUG_CLIENT_HOST: ${PHP_XDEBUG_CLIENT_HOST}
                SYMFONY_CLI_VERSION: 4.23.2
        ports:
            - "${PHP_PORT}:9001"
        user: ${UID}:${GID}
        volumes:
            - ./symfony:/var/www/symfony:cached
        depends_on:
            - db

    nginx:
        container_name: ${PROJECT_NAME}__nginx
        build:
            context: ./docker/nginx
            args:
                NGINX_SYMFONY_SERVER_NAME: ${NGINX_SYMFONY_SERVER_NAME}
        ports:
            - "${NGINX_PORT}:80"
        depends_on:
            - php
        environment:
            - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/conf.d
            - NGINX_ENVSUBST_TEMPLATE_DIR=/etc/nginx/templates
            - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.template
            - NGINX_SYMFONY_SERVER_NAME=${NGINX_SYMFONY_SERVER_NAME}
        volumes:
            - ./symfony:/var/www/symfony:cached
